# Utiliser une image Node.js légère
FROM node:18-slim

# Créer un répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . .

# Exposer le port utilisé par Vite
ENV PORT=5173
EXPOSE ${PORT}

# Démarrer le serveur de développement
CMD ["npm", "run", "dev"]